### ISSUE TITLE
Issue with Superstore.csv file

### ISSUE THREAD

**Issue by averyjmitchell** [PacktPublishing/Learning-Tableau-2020#1]
I am unable to download the superstore.csv file. When I click on the download button I am brought to another page containing the file's raw data.

**Comment by Sonawane-Karan26** [comment]
You can clone or download the entire repository and can access to respective files
OR
If the file is from any chapter, you can navigate to the file, view the raw file and then right clicking on the same page and doing a "Save as" can download the file.
Example: View raw > Right click > Save Page as ... > Save as .csv
